### PR TITLE
Add comment parsers and tests

### PR DESCRIPTION
**Pull request by kvverti**
Adds a line comment parser for `//` comments and a token delimiter parser that parses a (possibly empty) sequence of comments and whitespace

### CODE REVIEW

**Comment by io12** [comment]
Looks great!

**Comment by Alfriadox** [comment]
I merged master in here and resolved a conflict but otherwise this looks good. I will merge this in when CI passes.

**Comment by Alfriadox** [comment]
I also had to remove unknown-linux-musl targets because they were segfaulting for some reason. They are [tier 2](https://forge.rust-lang.org/release/platform-support.html) platforms so its fine if we don't support them

**Comment by Alfriadox** [comment]
Merging despite CI. Fixed on master.

**Pull request merged**
